obstacle_range: 5
raytrace_range: 3

footprint: [[0.2,0.35], [0.2,-0.35],[-0.75,-0.27],[-0.75,0.25]]
#robot_radius: ir_of_robot
inflation_radius: 0.1

observation_sources: laser_scan_sensor #, point_cloud_sensor

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: base_link, data_type: PointCloud2, topic: /transformed_pointcloud, marking: true, clearing: true}
